# Start this with:
#    docker-compose up
version: "3.9"
services:
  webapp:
    build:
      context: .
    image: textcritical
    container_name: textcritical
    ports:
      - "8080:8080"
    volumes:
       - ./var/db:/db
