# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-18 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_lexiconentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_born',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_died',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of death'),
        ),
        migrations.AlterField(
            model_name='lemma',
            name='reference_number',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='clitic',
            field=models.IntegerField(choices=[('', ''), (0, 'Proclitic'), (1, 'Enclitic'), (2, 'Mesoclitic'), (3, 'Endoclitic')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='comparative',
            field=models.IntegerField(choices=[('', ''), (0, 'Regular'), (1, 'Irregular')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='description',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='meaning',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='number',
            field=models.IntegerField(choices=[('', ''), (0, 'Singular'), (1, 'Dual'), (2, 'Plural')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='part_of_speech',
            field=models.IntegerField(choices=[('', ''), (0, 'Noun'), (1, 'Verb'), (2, 'Adverb'), (3, 'Pronoun'), (4, 'Adjective'), (5, 'Preposition'), (6, 'Conjunction'), (7, 'Interjection')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='person',
            field=models.IntegerField(choices=[('', ''), (1, 'First'), (2, 'Second'), (3, 'Third')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='superlative',
            field=models.IntegerField(choices=[('', ''), (0, 'Regular'), (1, 'Irregular')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='voice',
            field=models.IntegerField(choices=[('', ''), (0, 'Active'), (1, 'Middle'), (2, 'Passive'), (3, 'Middle/Passive')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='date_written',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date written'),
        ),
    ]
