# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-28 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_auto_20220318_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexiconentry',
            name='lemma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reader.Lemma'),
        ),
    ]
