# Generated by Django 3.2.13 on 2022-04-12 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_auto_20220327_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexiconentry',
            name='lemma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reader.lemma'),
        ),
    ]
