# Generated by Django 3.2.13 on 2022-08-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_alter_lexiconentry_lemma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddescription',
            name='adverb',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='expletive',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='feminine',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='geog_name',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='indeclinable',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='infinitive',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='masculine',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='movable_nu',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='neuter',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='numeral',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='participle',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='particle',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worddescription',
            name='poetic',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
