# Generated by Django 3.2.15 on 2022-09-10 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0008_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='value',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='name',
            new_name='title',
        ),
    ]
