# Generated by Django 3.2.15 on 2022-09-17 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0009_auto_20220909_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reader.work'),
        ),
    ]
