# Generated by Django 3.2.18 on 2023-04-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0010_note_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='division',
        ),
        migrations.RemoveField(
            model_name='note',
            name='verse',
        ),
        migrations.RemoveField(
            model_name='note',
            name='work',
        ),
        migrations.AddField(
            model_name='note',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='division_full_descriptor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='division_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='verse_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='verse_indicator',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='work_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='work_title_slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
