# Generated by Django 3.2.18 on 2023-04-20 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0011_auto_20230414_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='division_full_descriptor',
        ),
        migrations.RemoveField(
            model_name='note',
            name='division_id',
        ),
        migrations.RemoveField(
            model_name='note',
            name='verse_id',
        ),
        migrations.RemoveField(
            model_name='note',
            name='verse_indicator',
        ),
        migrations.RemoveField(
            model_name='note',
            name='work_id',
        ),
        migrations.RemoveField(
            model_name='note',
            name='work_title_slug',
        ),
        migrations.CreateModel(
            name='NoteReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.IntegerField(null=True)),
                ('work_title_slug', models.SlugField(null=True)),
                ('division_id', models.IntegerField(null=True)),
                ('division_full_descriptor', models.CharField(max_length=100, null=True)),
                ('verse_id', models.IntegerField(null=True)),
                ('verse_indicator', models.CharField(max_length=10, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.note')),
            ],
        ),
    ]
