# Start this with:
#    docker-compose up
version: "3.9"
services:
  textcritical_dev_container:
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    network_mode: "bridge"
    build:
      context: ..
      dockerfile: ./Dockerfile
    #image: textcritical_dev_container
    #container_name: textcritical_dev_container
    ports:
      - "30080:8080"
      - "8081:8081"
    volumes:
      - ..:/workspace:cached

